all:
  children:
    web:
      hosts:
        server-one:
          ansible_host: ec2-34-210-90-114.us-west-2.compute.amazonaws.com
        server-two:
          ansible_host: ec2-54-186-255-8.us-west-2.compute.amazonaws.com